### PR TITLE
restore v0.4 behavior on v0.5, fixes #880

### LINKED ISSUE #880: Inexact error on 0.5
I discovered the following code crashes on 0.5-rc3 when reworking the documentation (https://github.com/dcjones/Gadfly.jl/pull/879)

```julia
julia> using RDatasets

julia> using Gadfly

julia> plot(dataset("ggplot2", "diamonds"), x="Price", color="Cut",
            Geom.histogram(bincount=30, density=true))
Error showing value of type Gadfly.Plot:
ERROR: InexactError()
 in copy!(::Base.LinearFast, ::Array{Int64,1}, ::Base.LinearFast, ::Array{Float64,1}) at ./abstractarray.jl:559
 in broadcast!(::Base.#identity, ::Array{Int64,1}, ::Array{Float64,1}) at ./broadcast.jl:24
 in apply_statistic(::Gadfly.Stat.HistogramStatistic, ::Dict{Symbol,Gadfly.ScaleElement}, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics) at /Users/tamasnagy/.julia/v0.5/Gadfly/src/statistics.jl:330
 in apply_statistics(::Array{Gadfly.StatisticElement,1}, ::Dict{Symbol,Gadfly.ScaleElement}, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics) at /Users/tamasnagy/.julia/v0.5/Gadfly/src/statistics.jl:38
 in render_prepare(::Gadfly.Plot) at /Users/tamasnagy/.julia/v0.5/Gadfly/src/Gadfly.jl:740
 in render(::Gadfly.Plot) at /Users/tamasnagy/.julia/v0.5/Gadfly/src/Gadfly.jl:799
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/html")}, ::Gadfly.Plot) at /Users/tamasnagy/.julia/v0.5/Gadfly/src/Gadfly.jl:1062
 in macro expansion at ./multimedia.jl:143 [inlined]
 in display(::Gadfly.Plot) at /Users/tamasnagy/.julia/v0.5/Gadfly/src/Gadfly.jl:1014
 in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:154
 in print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:139
 in (::Base.REPL.##22#23{Bool,Base.REPL.##33#42{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:652
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1579
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:903
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##930#931) at ./REPL.jl:188
 in _start() at ./client.jl:360
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?

julia> versioninfo()
Julia Version 0.5.0-rc3+0
Commit e6f843b (2016-08-22 23:43 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

```

### PR DESCRIPTION
**Pull request by tlnagy**
also add test for histogram with density=true

### CODE REVIEW

File: src/statistics.jl [hunk 1]
```diff
@@ -327,7 +327,7 @@ function apply_statistic(stat::HistogramStatistic,
             x_min = Gadfly.concrete_minimum(values)
             span = x_max - x_min
             binwidth = span / d
-            bincounts ./= sum(bincounts) * binwidth
+            bincounts = bincounts ./ sum(bincounts) * binwidth
```
Comment (shashi) [inline src/statistics.jl]: I thought this was safe.

There's one more occurrence of this same line in this file. Does that work OK?

Comment (tlnagy) [inline src/statistics.jl]: It's not. This line causes an `InexactError` in the case that `binwidth` is a float. `bincounts` is always an integer array and with the new meaning of `./=` on v0.5 we are trying to do an in-place update of integer array using floats causing a type coercion error, i.e. the `InexactError`.

julia v0.4: 
```julia
julia> a = [1,2,3]
3-element Array{Int64,1}:
 1
 2
 3

julia> a ./= 2.0
3-element Array{Float64,1}:
 0.5
 1.0
 1.5
```

julia v0.5-rc3
```julia
julia> a = [1,2,3]
3-element Array{Int64,1}:
 1
 2
 3

julia> a ./= 2.0
ERROR: InexactError()
 in copy!(::Base.LinearFast, ::Array{Int64,1}, ::Base.LinearFast, ::Array{Float64,1}) at ./abstractarray.jl:559
 in broadcast!(::Base.#identity, ::Array{Int64,1}, ::Array{Float64,1}) at ./broadcast.jl:24
```

**Comment by tlnagy** [comment]
I wasn't able to get the other `./=` to break, but it looks like it is the same exact style of operation so it would probably be best to replace it. I'm going push that and squash.

File: src/statistics.jl (hunk 1 above)
Comment (shashi) [inline src/statistics.jl]: good detective work!

@stevengj pinging you to let you know about this.

**Comment by shashi** [comment]
wow that build hasn't started in a good 4 hours.

File: src/statistics.jl (hunk 1 above)
Comment (tlnagy) [inline src/statistics.jl]: I think that is the intended behavior.

**Comment by tlnagy** [comment]
Yeah, at least tests are passing on nightlies now that https://github.com/JuliaStats/KernelDensity.jl/issues/36 was resolved.

Would it be possible to merge this? Tests pass on Linux on Travis and they pass on my local OS X machine. It would be nice for #879

**Comment by tkelman** [comment]
https://www.traviscistatus.com/incidents/4mvp857qx8bw

**Comment by tlnagy** [comment]
Thanks @tkelman! That explains why `Documenter.jl` tests were stalling on OS X too. Hopefully travis gets that back up and running soon.

File: src/statistics.jl (hunk 1 above)
Comment (stevengj) [inline src/statistics.jl]: Yes, that is the intended behavior.

Comment (stevengj) [inline src/statistics.jl]: (In-place, fused vectorized operations will be a key feature in Julia 0.6.  The fact that it catches a type instability is a bonus. :wink:)

Comment (stevengj) [inline src/statistics.jl]: Note that your new 0.4-style code is still type-unstable.  If I were you, I'd use a different variable name (`binmean`?) for the normalized `bincounts`.

Comment (tlnagy) [inline src/statistics.jl]: > Note that your new 0.4-style code is still type-unstable.

All of Gadfly is type-unstable 😂 haha.

> If I were you, I'd use a different variable name (`binmean`?) for the normalized `bincounts`.

Why is having a new variable better? `binmean` will still sometimes be an `Int` sometimes a `Float64`.

Comment (stevengj) [inline src/statistics.jl]: No, I mean do `binmean = bincounts ./ sum(bincounts) * binwidth`.   Then `bincounts` is always an array of integers, and `binmean` is always an array of floats.   In subsequent lines, work with `binmean`.

(I realize that it is probably not performance critical to be type-stable here, but it is better style in Julia to retain type stability if it is not too hard.)

Comment (tlnagy) [inline src/statistics.jl]: Ah, I see what you mean.
